### ISSUE TITLE
login issues yet again...

### ISSUE THREAD

**Issue by Jwminva** [mysticcoders/voicenotes-sync#67]
login issues yet again...wtf are you guys doing?! There's not even an update! That and the tags no longer display in the frontmatter and haven't since the last episode of these issues!

**Comment by kinabalu** [comment]
Please understand that the sync plugin is a different piece of code from the voicenotes.com webapp. If there is something new happening with login, it may take folks who can copy and paste developer tools errors in the logs to help us see why this may be happening.

**Comment by donjjones** [comment]
Hello!  I'd be more than happy to provide whatever logs for this issue, just let me know what ones you need.  I've experienced the login issue and I think it's when my Obsidian mobile syncs plugin settings it just loses the config somehow.  Let me know and I'll give you whatever is needed.  Thanks for a great plugin!

**Comment by abolwell** [comment]
Getting consistently logged out after manual sync when logged in either via password or token.
Voicenotes Sync version: 0.0.30-beta3
Console log below after logging in using auth token and selecting Manual Sync (full)

loginUrl: https://api.voicenotes.com/api/auth/login
plugin:voicenotes-sync:1538 Error: Request failed, status 500
    at new t (app.js:1:1230945)
    at zA (app.js:1:1231137)
    at app.js:1:1231816
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
eval @ plugin:voicenotes-sync:1538
plugin:voicenotes-sync:1540 500
eval @ plugin:voicenotes-sync:1540
plugin:voicenotes-sync:1542 undefined
eval @ plugin:voicenotes-sync:1542
plugin:voicenotes-sync:1545 undefined
eval @ plugin:voicenotes-sync:1545
plugin:voicenotes-sync:1548 Object
eval @ plugin:voicenotes-sync:1548
plugin:voicenotes-sync:1538 Error: Request failed, status 500
    at new t (app.js:1:1230945)
    at zA (app.js:1:1231137)
    at app.js:1:1231816
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
eval @ plugin:voicenotes-sync:1538
plugin:voicenotes-sync:1540 500
eval @ plugin:voicenotes-sync:1540
plugin:voicenotes-sync:1542 undefined
eval @ plugin:voicenotes-sync:1542
plugin:voicenotes-sync:1545 undefined
eval @ plugin:voicenotes-sync:1545
plugin:voicenotes-sync:1548 Object
eval @ plugin:voicenotes-sync:1548
plugin:voicenotes-sync:1538 Error: Request failed, status 500
    at new t (app.js:1:1230945)
    at zA (app.js:1:1231137)
    at app.js:1:1231816
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
eval @ plugin:voicenotes-sync:1538
plugin:voicenotes-sync:1540 500
eval @ plugin:voicenotes-sync:1540
plugin:voicenotes-sync:1542 undefined
eval @ plugin:voicenotes-sync:1542
plugin:voicenotes-sync:1545 undefined
eval @ plugin:voicenotes-sync:1545
plugin:voicenotes-sync:1548 Object
eval @ plugin:voicenotes-sync:1548
plugin:voicenotes-sync:1538 Error: Request failed, status 500
    at new t (app.js:1:1230945)
    at zA (app.js:1:1231137)
    at app.js:1:1231816
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
eval @ plugin:voicenotes-sync:1538
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1540 500
eval @ plugin:voicenotes-sync:1540
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1542 undefined
eval @ plugin:voicenotes-sync:1542
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1545 undefined
eval @ plugin:voicenotes-sync:1545
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1548 {cache-control: 'no-cache, private', cf-cache-status: 'DYNAMIC', cf-ray: '911fcc23cc50db59-LAX', connection: 'keep-alive', content-type: 'application/json', …}
eval @ plugin:voicenotes-sync:1548
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1538 Error: Request failed, status 500
    at new t (app.js:1:1230945)
    at zA (app.js:1:1231137)
    at app.js:1:1231816
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
eval @ plugin:voicenotes-sync:1538
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1540 500
eval @ plugin:voicenotes-sync:1540
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1542 undefined
eval @ plugin:voicenotes-sync:1542
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1545 undefined
eval @ plugin:voicenotes-sync:1545
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1548 {cache-control: 'no-cache, private', cf-cache-status: 'DYNAMIC', cf-ray: '911fcc249d93db59-LAX', connection: 'keep-alive', content-type: 'application/json', …}
eval @ plugin:voicenotes-sync:1548
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1538 Error: Request failed, status 500
    at new t (app.js:1:1230945)
    at zA (app.js:1:1231137)
    at app.js:1:1231816
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
eval @ plugin:voicenotes-sync:1538
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1540 500
eval @ plugin:voicenotes-sync:1540
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1542 undefined
eval @ plugin:voicenotes-sync:1542
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1545 undefined
eval @ plugin:voicenotes-sync:1545
rejected @ plugin:voicenotes-sync:33
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
processNote @ plugin:voicenotes-sync:1404
eval @ plugin:voicenotes-sync:1591
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
fulfilled @ plugin:voicenotes-sync:32
Promise.then
step @ plugin:voicenotes-sync:34
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
sync @ plugin:voicenotes-sync:1561
eval @ plugin:voicenotes-sync:474
eval @ plugin:voicenotes-sync:35
__awaiter @ plugin:voicenotes-sync:31
eval @ plugin:voicenotes-sync:471
(anonymous) @ app.js:1
plugin:voicenotes-sync:1548 {cache-control: 'no-cache, private', cf-cache-status: 'DYNAMIC', cf-ray: '911fcc255eafdb59-LAX', connection: 'keep-alive', content-type: 'application/json', …}

**Comment by Jwminva** [comment]
Yeah it logged me out too for same reasons but it happens so often I don't pay as much attention.

The voicenotes app for Android doesn't work either after they updated it. I have to use mobile browser instead which works fine.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Kageetai** [comment]
Hey, I seem to have the same or similar issue.
Whenever Obsidian is restarted, especially on mobile, I am logged out of Voicenotes with this plugin. I have tried both login variants, password or token.

**Comment by Jwminva** [comment]
Yeah this has been happening for a long time now like several months at least. It's annoying because it's not predictable and it happens but it's not impossible to deal with. That said I don't know how to use the token login is that any more consistent? As far as I know I don't have a token only a traditional email login for the obsidian app.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Kageetai** [comment]
> That said I don't know how to use the token login is that any more consistent? As far as I know I don't have a token only a traditional email login for the obsidian app.

Token Login means using the Voicenotes token that is being generated when logging into Voicenotes without using the username and password directly. For that it's necessary to open the browsers dev tools inside Voicenotes and find that token, so it's more fore advanced users.

Also it doesn't seem any more reliable unfortunately...

**Comment by andyylin** [comment]
What about having a notification when sync fails or the plugin isn't logged in as a temporary workaround?

**Comment by Jwminva** [comment]
Yeah maybe but we'll be getting a lot of notifications. I mean this like a daily occurrence. It happened today in fact.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by geekiam23** [comment]
I'm running into the same issue. I see that @hjamet submitted a PR for this issue. Would that PR fix the issues?

**Comment by kinabalu** [comment]
Please re-test with 0.0.31 and re-open this ticket if still seeing an issue. Major refactoring was done and tests added to the API integration which I hope will solve some of these remaining issues
